version: "3"
services:
  app:
    container_name: svelte-auth-firebase
    working_dir: /app
    build:
      target: dev
    volumes:
      - ./src:/app/src
      - ./.svelte-kit/:/app/.svelte-kit
    ports:
      - 3000:3000
